In [1]:
import torch
print(torch.__version__)

2.10.0+cpu


## Creating Tensors

In [2]:
# empty()
torch.empty(2,3)

tensor([[1.3452e-43, 0.0000e+00, 6.7262e-44],
        [0.0000e+00, 1.1445e-40, 0.0000e+00]])

In [3]:
# zeros()
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# ones
torch.ones(1,4)

tensor([[1., 1., 1., 1.]])

In [6]:
# rand() -> this gives random value every time you run this
torch.rand(2,3)

tensor([[0.1708, 0.9977, 0.0416],
        [0.5179, 0.6744, 0.4231]])

In [7]:
# if you want to produce the same random values everytime you run the code set manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [8]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
# other ways similar to numpy
torch.arange(5)
torch.linspace(2,8,10)
torch.eye(4)
torch.full((3,5),10)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])

## Tensor Shapes

In [14]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
x.shape

torch.Size([2, 3])

In [18]:
# created tensor similar to already have tensor
torch.empty_like(x)

tensor([[    139869021674928,     139869021674928,                   0],
        [                  0,                   0, 7310593858020254331]])

In [19]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [20]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

## Tensors Data Type

In [21]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
x.dtype

torch.int64

In [23]:
# assign data type to tensors
torch.tensor([1,2,3,4], dtype=torch.float32)

tensor([1., 2., 3., 4.])

In [24]:
# to() -> function to convert the datatype
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Mathematical Operations

### 1. Scaler Operation

In [26]:
x = torch.rand(2,2)
x

tensor([[0.1217, 0.7356],
        [0.7118, 0.7876]])

In [31]:
# Scaler Operations
# addition
x+2
# substraction
x-2
# Multiplication
x*2
# Division
x/3
# int division
(x*100)//3
# mod
x%2
# power
x**2

tensor([[0.0148, 0.5411],
        [0.5066, 0.6203]])

### 2. Element-Wise Operation

In [32]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.4183, 0.9014, 0.9969],
        [0.7565, 0.2239, 0.3023]])
tensor([[0.1784, 0.8238, 0.5557],
        [0.9770, 0.4440, 0.9478]])


In [33]:
# addition
a+b

tensor([[0.5967, 1.7253, 1.5526],
        [1.7335, 0.6679, 1.2502]])

In [34]:
# subtraction
a-b

tensor([[ 0.2399,  0.0776,  0.4411],
        [-0.2205, -0.2201, -0.6455]])

In [35]:
# Division
a/b

tensor([[2.3445, 1.0942, 1.7938],
        [0.7743, 0.5042, 0.3190]])

In [36]:
# Multiplication
a*b

tensor([[0.0746, 0.7426, 0.5540],
        [0.7391, 0.0994, 0.2866]])

In [37]:
# Power
a**b

tensor([[0.8560, 0.9180, 0.9983],
        [0.7614, 0.5145, 0.3218]])

In [38]:
c = torch.tensor([-1,2,-4,5,-6])
c

tensor([-1,  2, -4,  5, -6])

In [39]:
# abs
torch.abs(c)

tensor([1, 2, 4, 5, 6])

In [42]:
# negative()
c.negative()

tensor([ 1, -2,  4, -5,  6])

In [43]:
# clamp
torch.clamp(c,min = 2, max= 9)

tensor([2, 2, 2, 5, 2])

### 3. Reduction Operation

In [53]:
t = torch.randint(size = (2,3), low = 2,high = 5,dtype = torch.float32)
t

tensor([[4., 4., 2.],
        [4., 2., 2.]])

In [49]:
# sum
torch.sum(t)

tensor(16)

In [51]:
# column wise sum
torch.sum(t, dim = 0)
# row wise sum
torch.sum(t,dim = 1)

tensor([10,  6])

In [54]:
# mean
torch.mean(t)

tensor(3.)

In [55]:
# column wise mean
torch.mean(t,dim = 0)


tensor([4., 3., 2.])

In [56]:
# median
torch.median(t)

tensor(2.)

In [59]:
# max and min
torch.max(t)
torch.min(t)

tensor(2.)

In [60]:
# std
torch.std(t)

tensor(1.0954)

In [61]:
# argmin()
torch.argmin(t)

tensor(2)

In [62]:
# argmax()
torch.argmax(t)

tensor(0)

### 4. Matrix Operations

In [64]:
a = torch.randint(size = (2,3), low = 0, high = 10)
b = torch.randint(size = (3,2), low = 0, high = 10)

print(a)
print(b)

tensor([[9, 7, 5],
        [9, 8, 9]])
tensor([[7, 9],
        [2, 6],
        [7, 7]])


In [65]:
# Matrix Multiplication
torch.matmul(a,b)

tensor([[112, 158],
        [142, 192]])

In [67]:
# transpose
torch.transpose(a,0,1)

tensor([[9, 9],
        [7, 8],
        [5, 9]])

In [68]:
# det
torch.det(a)

RuntimeError: linalg.det: A must be batches of square matrices, but they are 2 by 3 matrices

In [69]:
# inverse()
torch.inverse(a)

RuntimeError: linalg.inv: A must be batches of square matrices, but they are 2 by 3 matrices

### 5. Comparison Operations

In [70]:
a = torch.randint(size = (2,3), low = 0, high = 10)
b = torch.randint(size = (2,3), low = 0, high = 10)
print(a)
print(b)

tensor([[8, 3, 6],
        [1, 5, 5]])
tensor([[0, 4, 3],
        [8, 8, 3]])


In [72]:
# This is also element wise
# greater than
a > b

# less than
a < b



tensor([[False,  True, False],
        [ True,  True, False]])

### 6. Special Functions

In [78]:
k = torch.randint(size = (2,3), low = 0, high = 10,dtype = torch.float32)
k

tensor([[8., 4., 7.],
        [2., 3., 8.]])

In [74]:
# log
torch.log(k)

tensor([[1.0986, 1.6094,   -inf],
        [1.7918, 1.3863,   -inf]])

In [75]:
# exp
torch.exp(k)

tensor([[ 20.0855, 148.4132,   1.0000],
        [403.4288,  54.5981,   1.0000]])

In [76]:
torch.sqrt(k)

tensor([[1.7321, 2.2361, 0.0000],
        [2.4495, 2.0000, 0.0000]])

In [77]:
torch.sigmoid(k)

tensor([[0.9526, 0.9933, 0.5000],
        [0.9975, 0.9820, 0.5000]])

In [80]:
torch.softmax(k,dim=0)

tensor([[0.9975, 0.7311, 0.2689],
        [0.0025, 0.2689, 0.7311]])

In [81]:
torch.relu(k)

tensor([[8., 4., 7.],
        [2., 3., 8.]])

## inplace Operations

In [82]:
# to make the operations inplace
# add_
# relu_

# add _ in front of operation name and it will become inplace operations

### Copying a Tensor

In [ ]:
# clone()
b = a.clone()
# stores b in different memory location


## Tensors on GPU

In [83]:
torch.cuda.is_available()

False

In [ ]:
device = torch.device('cude')
# only change in operations is when you create a tensor pass a parameter device = device

## Reshaping Tensors

In [84]:
a = torch.ones(4,4)

In [87]:
a.reshape((2,2,2,2))

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [88]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [90]:
# unsqeeze -> add extra dimension
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])