In [1]:
!pip3 install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 28.4 MB/s  0:00:00


## Numpy Basics:
### Defination: 
 - NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidi-
mensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for
fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier
transforms, basic linear algebra, basic statistical operations, random simulation and much more.

 - At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data
types, with many operations being performed in compiled code for performance.

### Features:
 - Fized size at creation, Changing the size result in creation of new and deletion of original.
 - required to be of the same data type, and thus will be the same size in memory.
 - facilitate advanced mathematical and other types of operations on large numbers of data.
 - plethora of scientific and mathematical Python-based packages are using NumPy arrays.

### Vectorisation and Braodcasting
 - Vectorization describes the absence of any explicit looping, indexing, etc., in the code - these things are taking place, of course, just “behind the scenes” in optimized, pre-compiled C code.
 - Advantages:
   - Code is more concise and easier to read
   - Fewer line of code hence fewer bugs
   - code more closely resembles standard mathematical notation
 - Broadcasting is the term used to describe the implicit element-by-element behavior of operations; generally speaking, in NumPy all operations, not just arithmetic operations, but logical, bit-wise, functional, etc., behave in this implicit element-by-element fashion, i.e., they broadcast.

### The Basics:
- Numpy's main object is a homogenous multidimensinal Array (ndarray class).
- In Numpy dimensions are called ``` axes```
- Some important attributes os ndarray class's object are:
    - ndarray.ndim ``` number of axes (dimensions) of the array```
    - ndarray.shape ``` tuple of integers indicating the size of the array in each dimension ```
    - ndarray.size ``` the total number of elements of the array ```
    - ndarray.dtype ```an object describing the type of the elements in the array.```
    - ndarray.itemsize ``` the size in bytes of each element of the array. ```

In [2]:
import numpy as np

### Array Creation:
1. Create an array from a regular Python list or tuple using the `array` function.
    ```
    np.array([(1.5, 2, 3), (4, 5, 6)])
    ```
    
2. Using `np.zeros` or `np.ones` to create an array filled with either 0 or 1 initially
    ```
    np.zeros((3, 4))
    ```
    It takes a tuple dipicting shape of the array as argument, also can take one more optional argument dtype = np.int16 or np.float64

   
3. Using `arange` function.
    ```
   np.arange(10, 30, 5) 
   ```
   taking 3 arguments as follow start, end, step which is analogue to range function in python
   step can also take float argument
   - When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:
     ```
     np.linspace(0, 2, 9) 
     ```
   - 9 numbers from 0 to 2
   

In [29]:
# One dimensional array
a = np.array([1,2,3])
print(a)

# Two Dimensional Array
b = np.array([[1,2,3],[4,5,6]])
print(b)

print("\nArray of zeros with default datatype: ")
a0 = np.zeros((3,4))
print(a0)

print("\nArray of zeros with int datatype: ")
b0 = np.zeros((3,4),dtype = np.int64)
print(b0)

print("\nArray of ones with default datatype: ")
a1 = np.ones((4,3))
print(a1)

print("\nArray of ones with int datatype:")
b1 = np.ones((4,3),dtype = np.int16)
print(b1)

print("\nArray created using arange function with int step argument")
arr = np.arange(10,90,5)
print(arr)

print("\nArray created using arange function with float step argument")
arr1 = np.arange(0,5,0.3)
print(arr1)
print("Number of elements: {}\n".format(arr1.size))
# As we can see from the output no of values here cannot be determined

print("Array created using linspace")
arr2 = np.linspace(0,2,9)
print(arr2)
print("Number of elements : {}".format(arr2.size))

[1 2 3]
[[1 2 3]
 [4 5 6]]

Array of zeros with default datatype: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array of zeros with int datatype: 
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Array of ones with default datatype: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array of ones with int datatype:
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

Array created using arange function with int step argument
[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85]

Array created using arange function with float step argument
[0.  0.3 0.6 0.9 1.2 1.5 1.8 2.1 2.4 2.7 3.  3.3 3.6 3.9 4.2 4.5 4.8]
Number of elements: 17

Array created using linspace
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
Number of elements : 9


### Basic Operations
- Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.
- operations, such as += and *=, act in place to modify an existing array rather than create a new one.
- The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:
- Some of the unary operation on arrays are implemented as method in ndarray class, including: sum,max,min,cumsin etc.
  - By default all such methods are applied to matrix row wise but you can specify the axis to apply the operation.
  - Axis 0 = Column
  - Axis 1 = Row

```Note: When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).```


In [25]:
# Operations on Array
a = np.array([20,30,40,50])
b = np.arange(4)
print("First Array: ",a)
print("\nSecond Array: ",b)

# Subtraction
c = a-b
print("Subtraction: ",c)

# Addition
c = a+b
print("Addition:",c)

# Multiplication
c = a*b
print("Multiplication: ",c)

# Division
c = a//b
print("Division:",c)

# Power
print("Power: ",b**2)

a < 25

# Operation on Matrix (2d Array)
A = np.array([[1, 1],[0, 1]])
B = np.array([[2, 0],[3, 4]])


print("First Matrix: \n",A)
print("\nSecond Matrix: \n",B)
# 1. Element Wise Multiplication
C = A*B
print("Element Wise Multiplication: \n",C)

# Matix product or dot product
C = A@B
print("Matrix Dot Product: \n",C)

b+=10
print(b)
b*=10
print(b)

First Array:  [20 30 40 50]

Second Array:  [0 1 2 3]
Subtraction:  [20 29 38 47]
Addition: [20 31 42 53]
Multiplication:  [  0  30  80 150]
Division: [ 0 30 20 16]
Power:  [0 1 4 9]
First Matrix: 
 [[1 1]
 [0 1]]

Second Matrix: 
 [[2 0]
 [3 4]]
Element Wise Multiplication: 
 [[2 0]
 [0 4]]
Matrix Dot Product: 
 [[5 4]
 [3 4]]
[10 11 12 13]
[100 110 120 130]


/var/folders/n2/xblt95t12h7cjhv3hf2dtsw00000gn/T/ipykernel_8996/998764561.py:20: RuntimeWarning: divide by zero encountered in floor_divide
  c = a//b


In [35]:
b = np.arange(12).reshape(3, 4)
print("Matrix: \n",b)

print("Sum of elements of Matrix: \n",b.sum())
print("Max element in matrix: \n",b.max())
print("Min element in matrix: \n",b.min())
print("Cummulative sum across each row: \n",b.cumsum())

print("\n\n")
print("Sum of elements of Matrix across columns: \n",b.sum(axis = 0))
print("Max element in matrix across rows: \n",b.max(axis = 1))
print("Min element in matrix across column: \n",b.min(axis = 0))
print("Cummulative sum across each row: \n",b.cumsum(axis = 1))

Matrix: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Sum of elements of Matrix: 
 66
Max element in matrix: 
 11
Min element in matrix: 
 0
Cummulative sum across each row: 
 [ 0  1  3  6 10 15 21 28 36 45 55 66]



Sum of elements of Matrix across columns: 
 [12 15 18 21]
Max element in matrix across rows: 
 [ 3  7 11]
Min element in matrix across column: 
 [0 1 2 3]
Cummulative sum across each row: 
 [[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


### Indexing, Slicing and Iterating:

1. One-Dimensional Array:
   - They are index,Sliced and Iterated more like Python lists
2. Multi-Dimensional Array:
   - Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas.
   - If you want to perform operation on each element use flat attribut of multd.

In [49]:
# One-Dimensional
a = np.arange(10)**3
print(a)

# Indexing - [index]
for i in range(0,a.size):
    print("Element at index {} is : {}".format(i,a[i]))

# Iteration
for i in a:
    print(i)

# Slicing
print(a[2:5])

[  0   1   8  27  64 125 216 343 512 729]
Element at index 0 is : 0
Element at index 1 is : 1
Element at index 2 is : 8
Element at index 3 is : 27
Element at index 4 is : 64
Element at index 5 is : 125
Element at index 6 is : 216
Element at index 7 is : 343
Element at index 8 is : 512
Element at index 9 is : 729
0
1
8
27
64
125
216
343
512
729
[ 8 27 64]


In [67]:
#  Multi-Dimensional Array
b = np.array([[ 0, 1, 2, 3],
[10, 11, 12, 13],
[20, 21, 22, 23],
[30, 31, 32, 33],
[40, 41, 42, 43]])

print(b)

# Indexing - [row,column] - return single value
print(b[2,3])

# 1st column from 0 to 3 index
print(b[0:3,1])

# 1st row from 1 to 3 index
print(b[1,1:3])

# each column from 1st row onwards
print(b[1:,:])

for i in b.flat:
    print(i) 

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21]
[11 12]
[[10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


### Reshape an Numpy Array
```reshape``` method of ndarray class will give a new shape to an array without changing the data. Just remember that when you use
the reshape method, the array you want to produce needs to have the same number of elements as the original array. 

In [9]:
a= np.arange(8)
print(a.reshape(4,2))
print(a.reshape(2,4))
print(a.reshape(1,2,4))

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 2 3]
 [4 5 6 7]]
[[[0 1 2 3]
  [4 5 6 7]]]


### Index & Slicing concepts:

1. I have already covered the basics of Indexing and Slicing in NumPy Array.
2. If you want to select values from your array that fulfill certain conditions

In [17]:
# 2. If you want to select values from your array that fulfill certain conditions
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# Print all the values less than 5
print(a[a<5])

# Select Elements that are divisible by 2
print(a[a%2==0])

# Satisfy 2 condition using & and | operators:
print(a[(a>2) & (a<11)])

print(a)
# print(alternative columns
print(a[:,::2])

# Print alternative rows
print(a[::2,:])

# to be continued...

[1 2 3 4]
[ 2  4  6  8 10 12]
[ 3  4  5  6  7  8  9 10]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[ 1  2  3  4]
 [ 9 10 11 12]]


### Unique items and count
* Use ```np.unique()``` to get the unique elements from you array.
  * To get the index of the unique elements use ```return_index``` argument and pass it as True.
  * to get the occurence of the unique elements use ```return_counts``` argument.


In [11]:
# 1-D Array
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
print(a)

print(np.unique(a))
print(np.unique(a,return_index = True))
print(np.unique(a,return_counts=True))

# 2-d Array
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
print(a_2d)
print(np.unique(a_2d)) # convert the 2d array to 1d array

# Unique elemnt in a column
print(np.unique(a_2d, axis = 0))

#unique elements in a row
print(np.unique(a_2d,axis = 1))

[11 11 12 13 14 15 16 17 12 13 11 14 18 19 20]
[11 12 13 14 15 16 17 18 19 20]
(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]), array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14]))
(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]), array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1]))
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


### Transposing & Reshaping
There are two methods to transpose the array: ```.T or .transpose()```

In [18]:
data = np.arange(6).reshape(3,2)
print(data)
print(data.reshape(2,3))
print(data.transpose())
print(data.T)

[[0 1]
 [2 3]
 [4 5]]
[[0 1 2]
 [3 4 5]]
[[0 2 4]
 [1 3 5]]
[[0 2 4]
 [1 3 5]]
